import argparse
from datetime import date, datetime
import os.path

import utilities
import recreate_interval


#commandline example : python script/main.py -d input/panacota_photo -c input/core_genome_photorhabdus_genus_features.csv -o results
def main():

    args = get_args()
    today_date = date.today()
    utilities.check_dir(args.outdir, today_date)
    ref_genome, list_genomes = utilities.ref_genome(args.indir, args.ref)
    utilities.combine_input(args.indir, f"{args.outdir}/{today_date}_TATdyn", list_genomes)


    #First we need to recreate each interval in each genome
    #Note: The first genome in your folder will be considered as reference or you can use -r --ref {genome_name} to set the given genome as the reference
    #This is important because the order of the interval will be based on this genome
    recreate_interval.ref_interval(ref_genome, args.core, f"{args.outdir}/{today_date}_TATdyn")
    if os.path.exists(f"{args.outdir}/{today_date}_TATdyn/1-core_intervals/Ref_{ref_genome}_intervals.tsv") == False:
        recreate_interval.check_interval(ref_genome, list_genomes, args.core, f"{args.outdir}/{today_date}_TATdyn")
    if os.path.exists(f"{args.outdir}/{today_date}_TATdyn/1-core_intervals/all_genomes_intervals.tsv") == False:
        recreate_interval.recreate_intervals(ref_genome, list_genomes, args.core, f"{args.outdir}/{today_date}_TATdyn")







def get_args():

    parser = argparse.ArgumentParser()

    parser.add_argument("--indir", "-d",
                        help = " (REQUIRED) Directory in which are located the proteins/gff/replicons generated by PanACoTA annotate", required = True)
    parser.add_argument("--core", "-c",
                help = "(REQUIRED) Core features files generated using PanACoTA corepers (strict 100%) followed by TAT_core2df.py script",
                required = True)
    parser.add_argument("--outdir", "-o",
                help ="(REQUIRED) Out directory in which the results will be stored",
                required = True)

    parser.add_argument("-r", "--ref",
                        help = "If you want to specify which genome in you dataset will serve as reference (default: the first in your dataset), \n Note: At least this genome needs to be fully assembled",
                        default = None
                        )


    parser.add_argument("--threads",
                        help = "Number of threads to use (default = 1) 0 for the max threads to use",
                        default = 1
                        )


    args = parser.parse_args()
    return args





if __name__ == "__main__":
    main()