import argparse
from datetime import date, datetime


import utilities
import HTgenes
import HCspot


#commandline : python script/main_2.py -c input/full_photo/count_full_photo_spot.xml --dir results/2022-12-06_TATdyn



def main():

    args = get_args()
    print(args.countfile)
    print(args.dir)

    HTgenes.determine_HTgenes(args.countfile, args.dir)








def get_args():

    parser = argparse.ArgumentParser()
    parser.add_argument("--countfile", "-c",
                        help = " (REQUIRED) The tab delimited file inferring the ancestral evolution of each spot generated by Count", required = True)

    parser.add_argument("--dir", "-d",
                        help = " (REQUIRED) Outdir in which there are the results from the first script", required = True)
    
    
    args = parser.parse_args()
    return args


if __name__ == "__main__":
    main()