import argparse
from datetime import date, datetime

import utilities
import recreate_interval


#commandline example : python script/main.py -d input/panacota_photo -c input/corefile -o results
def main():

    args = get_args()
    today_date = date.today()
    utilities.check_dir(args.outdir, today_date)
    ref_genome = utilities.ref_genome(args.indir, args.ref)
    print(ref_genome)
    #First we need to recreate each interval in each genome
    #Note: The first genome in your folder will be considered as reference or you can use -r --ref {genome_name} to set the given genome as the reference
    #This is important because the order of the interval will be based on this genome
    recreate_interval.main()








def get_args():

    parser = argparse.ArgumentParser()

    parser.add_argument("--indir", "-d",
                        help = " (REQUIRED) Directory in which are located the proteins/gff/replicons generated by PanACoTA annotate", required = True)
    parser.add_argument("--core", "-c",
                help = "(REQUIRED) Core features files generated using PanACoTA corepers (strict 100%) followed by TAT_core2df.py script",
                required = True)
    parser.add_argument("--outdir", "-o",
                help ="(REQUIRED) Out directory in which the results will be stored",
                required = True)

    parser.add_argument("-r", "--ref",
                        help = "If you want to specify which genome in you dataset will serve as reference (default: the first in your dataset), \n Note: At least this genome needs to be fully assembled",
                        default = None
                        )


    parser.add_argument("--threads",
                        help = "Number of threads to use (default = 1) 0 for the max threads to use",
                        default = 1
                        )


    args = parser.parse_args()
    return args





if __name__ == "__main__":
    main()