import pandas as pd
import sys
import os
from Bio import SeqIO

def spot_defense_finder(spot_pangenome_file, prt_file, gff_file, outdir, **kwargs):
    n_core = kwargs.get("n_core", 1)

    # will run defense-finder for each spot and determine which spot might a defense spot integration see:
    # Systematic and quantitative view of the antiviral arsenal of prokaryotes F. Tesson et al, 2022
    # Also using PADLOC:  Payne, L. J., Todeschini, T. C., Wu, Y., Perry, B. J., Ronson, C. W., Fineran, P. C., Nobrega, F. L., Jackson, S. A. (2021) Identification and classification of antiviral defence systems in bacteria and archaea with PADLOC reveals new system types. Nucleic Acids Research, 49, 10868-10878. doi: https://doi.org/10/gzgh
    # First input file should be like the all_genomes_intervals.tsv file found in the 1-core_intervals folder generated by TATdyn.py,
    # Second input should be the protein sequences files concatenated into a single file in .faa format
    # Third file correspond to the concatanated gff file , NOTE : it will be useful if we decide to include padloc screening only

    df_spot_pangenome = pd.read_csv(spot_pangenome_file, sep ="\t")
    df_spot_pangenome.set_index("interval_number", inplace = True)
    df_spot_pangenome.dropna(axis = 0, how = "all", inplace = True)

    #need to format the prt file to use defense-finder (gembase format)
    print("Formating the prt file")
    str_prt = ""
    with open(prt_file, "r") as f:
        for line in f:
            if line.startswith(">"):
                line = line.split(" ")[0].split("_")[0][:-1]+"i_"+line.split("_")[1]
                str_prt += f'{line}\n'
            else:
                str_prt+= line

    with open(prt_file+"_formated.faa", "w") as f:
        f.write(str_prt)
    
    print("Running defense-finder")
    #running defense-finder for each genome
    os.system(f"defense-finder run -o {outdir} --db-type gembase {prt_file}_formated.faa")
    
    #running padloc for each genome
    # Did put PADLOC on a hold because it has problem being executed on WSL due t the init system.
    # might activate Systemd if defense-finder isn't enough to detect all systems
    # print("Running PADLOC")
    #os.system(f"conda run -n padloc padloc --faa {prt_file} --outdir {outdir} --cpu {n_core} --gff {gff_file}")

    #Parsing the results
    print("Parsing defense-finder results compared to the spot_pangenome previously generated")
    df_summary, df_spot_defense, str_systems_out_of_spotpangenome= defense_finder_parser(f"{outdir}/defense_finder_systems.tsv", df_spot_pangenome)
    df_summary.to_csv(f"{outdir}/0_summary_full_genome_defense_system_screening.tsv", sep = "\t", index = False)
    df_spot_defense.to_csv(f"{outdir}/1_spot_pangenome_defense_system.tsv", sep = "\t", index = False)
    with open(f"{outdir}/2_out_of_spotpangenome_defense_system.txt", "w") as f:
        f.write(str_systems_out_of_spotpangenome)



def defense_finder_parser(defense_finder_systems_file, df_spot_pangenome):

    #will create two files => one summary with the numbers in each genome of each type of Defense system
    # second file will be the corresponding spot to each system.
    df_defense = pd.read_csv(defense_finder_systems_file, sep = "\t")

    # creating first file
    df_defense["genome"] = df_defense.apply(lambda x: x["sys_id"].rsplit(".", 1)[0], axis = 1)

    d_summary = {}
    for genome in df_spot_pangenome.columns.tolist():
        d_summary[genome] = {}
        d_summary[genome]["Total"] = len(df_defense[df_defense["genome"] == genome])
        for defense_type in df_defense["type"].drop_duplicates().tolist():
            d_summary[genome][defense_type] = len(df_defense[(df_defense["genome"] == genome) & (df_defense["type"] == defense_type)])

    df_summary = pd.DataFrame.from_dict(d_summary, orient = "index")
    df_summary.reset_index(inplace = True)
    df_summary.rename(columns={"index":"Genome"}, inplace= True)

    # now associating each defense system identified to a spot.
    # for that we detect which interval contains both first gene and last gene of the system
    # note will create aswell a txt file with the systems that are not totally part of the spot-pangenome

    str_systems_out_of_spotpangenome = ""
    d_spot_defense = {}
    for i in range(df_spot_pangenome.index[-1]+1):
        d_spot_defense[i]= {}
        for defense_type in df_defense["type"].drop_duplicates().tolist():
            d_spot_defense[i][defense_type] = 0

    for row in df_defense.iterrows():
        if df_spot_pangenome[(df_spot_pangenome[row[1]["genome"]].str.contains(f"{row[1]['sys_beg']}", na = False)) & (df_spot_pangenome[row[1]["genome"]].str.contains(f"{row[1]['sys_end']}", na = False))].empty == False:
            d_spot_defense[df_spot_pangenome[(df_spot_pangenome[row[1]["genome"]].str.contains(f"{row[1]['sys_beg']}", na = False)) & (df_spot_pangenome[row[1]["genome"]].str.contains(f"{row[1]['sys_end']}", na = False))].index[0]][row[1]["type"]] += 1
        else :
            str_systems_out_of_spotpangenome += f"The following system was not detected within the given spot-pangenome : {row[1]['sys_id']}\t{row[1]['type']}\t{row[1]['protein_in_syst']}\n"

    df_spot_defense = pd.DataFrame.from_dict(d_spot_defense, orient = "index")
    df_spot_defense = df_spot_defense.loc[~(df_spot_defense == 0).all(axis=1)]
    df_spot_defense.reset_index(inplace = True)
    df_spot_defense.rename(columns={"index":"Spot_number"}, inplace= True)


    return df_summary, df_spot_defense, str_systems_out_of_spotpangenome



if __name__ == "__main__":
    spot_defense_finder(sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4], n_core= 12)

    # test commandline : 
    # python script/TAT_defense-finder.py results/2023-01-26_TATdyn_6_full_photo_nopb/1-core_intervals/all_genomes_intervals.tsv results/2023-01-26_TATdyn_6_full_photo_nopb/tmp/cat_proteins.prt results/2023-01-26_TATdyn_6_full_photo_nopb/tmp/Ph6fullphoto_concat.gff results/2023-01-26_TATdyn_6_full_photo_nopb/5-optional_defense-finder